entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  gptube_resolver:
    acme:
      email: gptube.team@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
