definitions:
  handlers.helloApiMessage:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/:
    get:
      description: get base api welcome response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.helloApiMessage'
      summary: Hello from the api
swagger: "2.0"
