basePath: /api
definitions:
  handlers.helloApiMessage:
    properties:
      message:
        type: string
    type: object
  models.BertAIResults:
    properties:
      errors_count:
        type: integer
      score_1:
        type: integer
      score_2:
        type: integer
      score_3:
        type: integer
      score_4:
        type: integer
      score_5:
        type: integer
      success_count:
        type: integer
    type: object
  models.YoutubeAnalysisLandingResults:
    properties:
      bert_results:
        $ref: '#/definitions/models.BertAIResults'
      video_id:
        type: string
      video_title:
        type: string
    type: object
  models.YoutubeAnalyzerLandingReqBody:
    properties:
      video_id:
        example: 1xoy8Q5o8ws
        type: string
      video_title:
        example: The Truth About Bun
        type: string
    type: object
  models.YoutubeAnalyzerLandingRespBody:
    properties:
      created_at:
        type: string
      email:
        type: string
      results:
        $ref: '#/definitions/models.YoutubeAnalysisLandingResults'
      video_id:
        type: string
      video_title:
        type: string
    type: object
  utils.HandleError.errorResponse:
    properties:
      error:
        example: an error ocurred
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: luckly083@gmail.com
    name: saul rojas coila
  description: This is the API documentation of GPTube
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GPTube API swagger docs
  version: "1.0"
paths:
  /api:
    get:
      description: An endpoint used to test the api stability
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.helloApiMessage'
      summary: Hello message from the api
  /api/youtube/analysis-landing:
    post:
      description: An endpoint used to do a simple analysis with the BERT model to
        show a result in the landing
      parameters:
      - description: Youtube video id
        in: body
        name: video
        required: true
        schema:
          $ref: '#/definitions/models.YoutubeAnalyzerLandingReqBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.YoutubeAnalyzerLandingRespBody'
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/models.YoutubeAnalyzerLandingRespBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HandleError.errorResponse'
      summary: Simple analysis with BERT model for the landing page
  /billing:
    get:
      description: An endpoint used to test the billing api stability
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.helloApiMessage'
      summary: Hello message from the billing api
swagger: "2.0"
