definitions:
  handlers.helloApiMessage:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api:
    get:
      description: An endpoint used to test the api stability
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.helloApiMessage'
      summary: Hello message from the api
  /billing:
    get:
      description: An endpoint used to test the billing api stability
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.helloApiMessage'
      summary: Hello message from the billing api
swagger: "2.0"
