/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersHelloApiMessage
 */
export interface HandlersHelloApiMessage {
    /**
     * 
     * @type {string}
     * @memberof HandlersHelloApiMessage
     */
    message?: string;
}

/**
 * Check if a given object implements the HandlersHelloApiMessage interface.
 */
export function instanceOfHandlersHelloApiMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HandlersHelloApiMessageFromJSON(json: any): HandlersHelloApiMessage {
    return HandlersHelloApiMessageFromJSONTyped(json, false);
}

export function HandlersHelloApiMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersHelloApiMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function HandlersHelloApiMessageToJSON(value?: HandlersHelloApiMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

