/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LemonsqueezyApiResponseRelationshipsSubscriptionInvoice } from './LemonsqueezyApiResponseRelationshipsSubscriptionInvoice';
import {
    LemonsqueezyApiResponseRelationshipsSubscriptionInvoiceFromJSON,
    LemonsqueezyApiResponseRelationshipsSubscriptionInvoiceFromJSONTyped,
    LemonsqueezyApiResponseRelationshipsSubscriptionInvoiceToJSON,
} from './LemonsqueezyApiResponseRelationshipsSubscriptionInvoice';
import type { LemonsqueezyApiResponseSelfLink } from './LemonsqueezyApiResponseSelfLink';
import {
    LemonsqueezyApiResponseSelfLinkFromJSON,
    LemonsqueezyApiResponseSelfLinkFromJSONTyped,
    LemonsqueezyApiResponseSelfLinkToJSON,
} from './LemonsqueezyApiResponseSelfLink';
import type { LemonsqueezySubscriptionInvoiceAttributes } from './LemonsqueezySubscriptionInvoiceAttributes';
import {
    LemonsqueezySubscriptionInvoiceAttributesFromJSON,
    LemonsqueezySubscriptionInvoiceAttributesFromJSONTyped,
    LemonsqueezySubscriptionInvoiceAttributesToJSON,
} from './LemonsqueezySubscriptionInvoiceAttributes';

/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice
 */
export interface LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice {
    /**
     * 
     * @type {LemonsqueezySubscriptionInvoiceAttributes}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice
     */
    attributes?: LemonsqueezySubscriptionInvoiceAttributes;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice
     */
    id?: string;
    /**
     * 
     * @type {LemonsqueezyApiResponseSelfLink}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice
     */
    links?: LemonsqueezyApiResponseSelfLink;
    /**
     * 
     * @type {LemonsqueezyApiResponseRelationshipsSubscriptionInvoice}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice
     */
    relationships?: LemonsqueezyApiResponseRelationshipsSubscriptionInvoice;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice
     */
    type?: string;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice interface.
 */
export function instanceOfLemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoiceFromJSON(json: any): LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice {
    return LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoiceFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': !exists(json, 'attributes') ? undefined : LemonsqueezySubscriptionInvoiceAttributesFromJSON(json['attributes']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'links': !exists(json, 'links') ? undefined : LemonsqueezyApiResponseSelfLinkFromJSON(json['links']),
        'relationships': !exists(json, 'relationships') ? undefined : LemonsqueezyApiResponseRelationshipsSubscriptionInvoiceFromJSON(json['relationships']),
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoiceToJSON(value?: LemonsqueezyApiResponseDataLemonsqueezySubscriptionInvoiceAttributesLemonsqueezyApiResponseRelationshipsSubscriptionInvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': LemonsqueezySubscriptionInvoiceAttributesToJSON(value.attributes),
        'id': value.id,
        'links': LemonsqueezyApiResponseSelfLinkToJSON(value.links),
        'relationships': LemonsqueezyApiResponseRelationshipsSubscriptionInvoiceToJSON(value.relationships),
        'type': value.type,
    };
}

