/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LemonsqueezyApiResponseRelationshipsDiscount } from './LemonsqueezyApiResponseRelationshipsDiscount';
import {
    LemonsqueezyApiResponseRelationshipsDiscountFromJSON,
    LemonsqueezyApiResponseRelationshipsDiscountFromJSONTyped,
    LemonsqueezyApiResponseRelationshipsDiscountToJSON,
} from './LemonsqueezyApiResponseRelationshipsDiscount';
import type { LemonsqueezyApiResponseSelfLink } from './LemonsqueezyApiResponseSelfLink';
import {
    LemonsqueezyApiResponseSelfLinkFromJSON,
    LemonsqueezyApiResponseSelfLinkFromJSONTyped,
    LemonsqueezyApiResponseSelfLinkToJSON,
} from './LemonsqueezyApiResponseSelfLink';
import type { LemonsqueezyCheckoutAttributes } from './LemonsqueezyCheckoutAttributes';
import {
    LemonsqueezyCheckoutAttributesFromJSON,
    LemonsqueezyCheckoutAttributesFromJSONTyped,
    LemonsqueezyCheckoutAttributesToJSON,
} from './LemonsqueezyCheckoutAttributes';

/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount
 */
export interface LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount {
    /**
     * 
     * @type {LemonsqueezyCheckoutAttributes}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount
     */
    attributes?: LemonsqueezyCheckoutAttributes;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount
     */
    id?: string;
    /**
     * 
     * @type {LemonsqueezyApiResponseSelfLink}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount
     */
    links?: LemonsqueezyApiResponseSelfLink;
    /**
     * 
     * @type {LemonsqueezyApiResponseRelationshipsDiscount}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount
     */
    relationships?: LemonsqueezyApiResponseRelationshipsDiscount;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount
     */
    type?: string;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount interface.
 */
export function instanceOfLemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscountFromJSON(json: any): LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount {
    return LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscountFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': !exists(json, 'attributes') ? undefined : LemonsqueezyCheckoutAttributesFromJSON(json['attributes']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'links': !exists(json, 'links') ? undefined : LemonsqueezyApiResponseSelfLinkFromJSON(json['links']),
        'relationships': !exists(json, 'relationships') ? undefined : LemonsqueezyApiResponseRelationshipsDiscountFromJSON(json['relationships']),
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscountToJSON(value?: LemonsqueezyApiResponseDataLemonsqueezyCheckoutAttributesLemonsqueezyApiResponseRelationshipsDiscount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': LemonsqueezyCheckoutAttributesToJSON(value.attributes),
        'id': value.id,
        'links': LemonsqueezyApiResponseSelfLinkToJSON(value.links),
        'relationships': LemonsqueezyApiResponseRelationshipsDiscountToJSON(value.relationships),
        'type': value.type,
    };
}

