/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LemonsqueezyApiResponseLink } from './LemonsqueezyApiResponseLink';
import {
    LemonsqueezyApiResponseLinkFromJSON,
    LemonsqueezyApiResponseLinkFromJSONTyped,
    LemonsqueezyApiResponseLinkToJSON,
} from './LemonsqueezyApiResponseLink';

/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseLinks
 */
export interface LemonsqueezyApiResponseLinks {
    /**
     * 
     * @type {LemonsqueezyApiResponseLink}
     * @memberof LemonsqueezyApiResponseLinks
     */
    links?: LemonsqueezyApiResponseLink;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseLinks interface.
 */
export function instanceOfLemonsqueezyApiResponseLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseLinksFromJSON(json: any): LemonsqueezyApiResponseLinks {
    return LemonsqueezyApiResponseLinksFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : LemonsqueezyApiResponseLinkFromJSON(json['links']),
    };
}

export function LemonsqueezyApiResponseLinksToJSON(value?: LemonsqueezyApiResponseLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': LemonsqueezyApiResponseLinkToJSON(value.links),
    };
}

