/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LemonsqueezyApiResponseLinks } from './LemonsqueezyApiResponseLinks';
import {
    LemonsqueezyApiResponseLinksFromJSON,
    LemonsqueezyApiResponseLinksFromJSONTyped,
    LemonsqueezyApiResponseLinksToJSON,
} from './LemonsqueezyApiResponseLinks';

/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseRelationshipsSubscription
 */
export interface LemonsqueezyApiResponseRelationshipsSubscription {
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsSubscription
     */
    customer?: LemonsqueezyApiResponseLinks;
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsSubscription
     */
    order?: LemonsqueezyApiResponseLinks;
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsSubscription
     */
    orderItem?: LemonsqueezyApiResponseLinks;
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsSubscription
     */
    product?: LemonsqueezyApiResponseLinks;
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsSubscription
     */
    store?: LemonsqueezyApiResponseLinks;
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsSubscription
     */
    subscriptionInvoices?: LemonsqueezyApiResponseLinks;
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsSubscription
     */
    subscriptionItems?: LemonsqueezyApiResponseLinks;
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsSubscription
     */
    variant?: LemonsqueezyApiResponseLinks;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseRelationshipsSubscription interface.
 */
export function instanceOfLemonsqueezyApiResponseRelationshipsSubscription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseRelationshipsSubscriptionFromJSON(json: any): LemonsqueezyApiResponseRelationshipsSubscription {
    return LemonsqueezyApiResponseRelationshipsSubscriptionFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseRelationshipsSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseRelationshipsSubscription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customer': !exists(json, 'customer') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['customer']),
        'order': !exists(json, 'order') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['order']),
        'orderItem': !exists(json, 'order-item') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['order-item']),
        'product': !exists(json, 'product') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['product']),
        'store': !exists(json, 'store') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['store']),
        'subscriptionInvoices': !exists(json, 'subscription-invoices') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['subscription-invoices']),
        'subscriptionItems': !exists(json, 'subscription-items') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['subscription-items']),
        'variant': !exists(json, 'variant') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['variant']),
    };
}

export function LemonsqueezyApiResponseRelationshipsSubscriptionToJSON(value?: LemonsqueezyApiResponseRelationshipsSubscription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customer': LemonsqueezyApiResponseLinksToJSON(value.customer),
        'order': LemonsqueezyApiResponseLinksToJSON(value.order),
        'order-item': LemonsqueezyApiResponseLinksToJSON(value.orderItem),
        'product': LemonsqueezyApiResponseLinksToJSON(value.product),
        'store': LemonsqueezyApiResponseLinksToJSON(value.store),
        'subscription-invoices': LemonsqueezyApiResponseLinksToJSON(value.subscriptionInvoices),
        'subscription-items': LemonsqueezyApiResponseLinksToJSON(value.subscriptionItems),
        'variant': LemonsqueezyApiResponseLinksToJSON(value.variant),
    };
}

