/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseListMetaPage
 */
export interface LemonsqueezyApiResponseListMetaPage {
    /**
     * 
     * @type {number}
     * @memberof LemonsqueezyApiResponseListMetaPage
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof LemonsqueezyApiResponseListMetaPage
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof LemonsqueezyApiResponseListMetaPage
     */
    lastPage?: number;
    /**
     * 
     * @type {number}
     * @memberof LemonsqueezyApiResponseListMetaPage
     */
    perPage?: number;
    /**
     * 
     * @type {number}
     * @memberof LemonsqueezyApiResponseListMetaPage
     */
    to?: number;
    /**
     * 
     * @type {number}
     * @memberof LemonsqueezyApiResponseListMetaPage
     */
    total?: number;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseListMetaPage interface.
 */
export function instanceOfLemonsqueezyApiResponseListMetaPage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseListMetaPageFromJSON(json: any): LemonsqueezyApiResponseListMetaPage {
    return LemonsqueezyApiResponseListMetaPageFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseListMetaPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseListMetaPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentPage': !exists(json, 'currentPage') ? undefined : json['currentPage'],
        'from': !exists(json, 'from') ? undefined : json['from'],
        'lastPage': !exists(json, 'lastPage') ? undefined : json['lastPage'],
        'perPage': !exists(json, 'perPage') ? undefined : json['perPage'],
        'to': !exists(json, 'to') ? undefined : json['to'],
        'total': !exists(json, 'total') ? undefined : json['total'],
    };
}

export function LemonsqueezyApiResponseListMetaPageToJSON(value?: LemonsqueezyApiResponseListMetaPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentPage': value.currentPage,
        'from': value.from,
        'lastPage': value.lastPage,
        'perPage': value.perPage,
        'to': value.to,
        'total': value.total,
    };
}

