/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseSelfLink
 */
export interface LemonsqueezyApiResponseSelfLink {
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseSelfLink
     */
    self?: string;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseSelfLink interface.
 */
export function instanceOfLemonsqueezyApiResponseSelfLink(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseSelfLinkFromJSON(json: any): LemonsqueezyApiResponseSelfLink {
    return LemonsqueezyApiResponseSelfLinkFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseSelfLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseSelfLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : json['self'],
    };
}

export function LemonsqueezyApiResponseSelfLinkToJSON(value?: LemonsqueezyApiResponseSelfLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': value.self,
    };
}

