/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseListLink
 */
export interface LemonsqueezyApiResponseListLink {
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseListLink
     */
    first?: string;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseListLink
     */
    last?: string;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseListLink
     */
    next?: string;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseListLink interface.
 */
export function instanceOfLemonsqueezyApiResponseListLink(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseListLinkFromJSON(json: any): LemonsqueezyApiResponseListLink {
    return LemonsqueezyApiResponseListLinkFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseListLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseListLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'first': !exists(json, 'first') ? undefined : json['first'],
        'last': !exists(json, 'last') ? undefined : json['last'],
        'next': !exists(json, 'next') ? undefined : json['next'],
    };
}

export function LemonsqueezyApiResponseListLinkToJSON(value?: LemonsqueezyApiResponseListLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first': value.first,
        'last': value.last,
        'next': value.next,
    };
}

