/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LemonsqueezyCheckoutProductOptions
 */
export interface LemonsqueezyCheckoutProductOptions {
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyCheckoutProductOptions
     */
    description?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof LemonsqueezyCheckoutProductOptions
     */
    enabledVariants?: Array<number>;
    /**
     * 
     * @type {Array<object>}
     * @memberof LemonsqueezyCheckoutProductOptions
     */
    media?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyCheckoutProductOptions
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyCheckoutProductOptions
     */
    receiptButtonText?: string;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyCheckoutProductOptions
     */
    receiptLinkUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyCheckoutProductOptions
     */
    receiptThankYouNote?: string;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyCheckoutProductOptions
     */
    redirectUrl?: string;
}

/**
 * Check if a given object implements the LemonsqueezyCheckoutProductOptions interface.
 */
export function instanceOfLemonsqueezyCheckoutProductOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyCheckoutProductOptionsFromJSON(json: any): LemonsqueezyCheckoutProductOptions {
    return LemonsqueezyCheckoutProductOptionsFromJSONTyped(json, false);
}

export function LemonsqueezyCheckoutProductOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyCheckoutProductOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'enabledVariants': !exists(json, 'enabled_variants') ? undefined : json['enabled_variants'],
        'media': !exists(json, 'media') ? undefined : json['media'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'receiptButtonText': !exists(json, 'receipt_button_text') ? undefined : json['receipt_button_text'],
        'receiptLinkUrl': !exists(json, 'receipt_link_url') ? undefined : json['receipt_link_url'],
        'receiptThankYouNote': !exists(json, 'receipt_thank_you_note') ? undefined : json['receipt_thank_you_note'],
        'redirectUrl': !exists(json, 'redirect_url') ? undefined : json['redirect_url'],
    };
}

export function LemonsqueezyCheckoutProductOptionsToJSON(value?: LemonsqueezyCheckoutProductOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'enabled_variants': value.enabledVariants,
        'media': value.media,
        'name': value.name,
        'receipt_button_text': value.receiptButtonText,
        'receipt_link_url': value.receiptLinkUrl,
        'receipt_thank_you_note': value.receiptThankYouNote,
        'redirect_url': value.redirectUrl,
    };
}

