/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LemonsqueezyApiResponseListMetaPage } from './LemonsqueezyApiResponseListMetaPage';
import {
    LemonsqueezyApiResponseListMetaPageFromJSON,
    LemonsqueezyApiResponseListMetaPageFromJSONTyped,
    LemonsqueezyApiResponseListMetaPageToJSON,
} from './LemonsqueezyApiResponseListMetaPage';

/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseListMeta
 */
export interface LemonsqueezyApiResponseListMeta {
    /**
     * 
     * @type {LemonsqueezyApiResponseListMetaPage}
     * @memberof LemonsqueezyApiResponseListMeta
     */
    page?: LemonsqueezyApiResponseListMetaPage;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseListMeta interface.
 */
export function instanceOfLemonsqueezyApiResponseListMeta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseListMetaFromJSON(json: any): LemonsqueezyApiResponseListMeta {
    return LemonsqueezyApiResponseListMetaFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseListMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseListMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : LemonsqueezyApiResponseListMetaPageFromJSON(json['page']),
    };
}

export function LemonsqueezyApiResponseListMetaToJSON(value?: LemonsqueezyApiResponseListMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': LemonsqueezyApiResponseListMetaPageToJSON(value.page),
    };
}

