/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LemonsqueezyApiResponseLinks } from './LemonsqueezyApiResponseLinks';
import {
    LemonsqueezyApiResponseLinksFromJSON,
    LemonsqueezyApiResponseLinksFromJSONTyped,
    LemonsqueezyApiResponseLinksToJSON,
} from './LemonsqueezyApiResponseLinks';

/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseRelationshipsDiscount
 */
export interface LemonsqueezyApiResponseRelationshipsDiscount {
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsDiscount
     */
    discountRedemptions?: LemonsqueezyApiResponseLinks;
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsDiscount
     */
    store?: LemonsqueezyApiResponseLinks;
    /**
     * 
     * @type {LemonsqueezyApiResponseLinks}
     * @memberof LemonsqueezyApiResponseRelationshipsDiscount
     */
    variants?: LemonsqueezyApiResponseLinks;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseRelationshipsDiscount interface.
 */
export function instanceOfLemonsqueezyApiResponseRelationshipsDiscount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseRelationshipsDiscountFromJSON(json: any): LemonsqueezyApiResponseRelationshipsDiscount {
    return LemonsqueezyApiResponseRelationshipsDiscountFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseRelationshipsDiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseRelationshipsDiscount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discountRedemptions': !exists(json, 'discount-redemptions') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['discount-redemptions']),
        'store': !exists(json, 'store') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['store']),
        'variants': !exists(json, 'variants') ? undefined : LemonsqueezyApiResponseLinksFromJSON(json['variants']),
    };
}

export function LemonsqueezyApiResponseRelationshipsDiscountToJSON(value?: LemonsqueezyApiResponseRelationshipsDiscount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discount-redemptions': LemonsqueezyApiResponseLinksToJSON(value.discountRedemptions),
        'store': LemonsqueezyApiResponseLinksToJSON(value.store),
        'variants': LemonsqueezyApiResponseLinksToJSON(value.variants),
    };
}

