/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LemonsqueezyApiResponseRelationshipsSubscription } from './LemonsqueezyApiResponseRelationshipsSubscription';
import {
    LemonsqueezyApiResponseRelationshipsSubscriptionFromJSON,
    LemonsqueezyApiResponseRelationshipsSubscriptionFromJSONTyped,
    LemonsqueezyApiResponseRelationshipsSubscriptionToJSON,
} from './LemonsqueezyApiResponseRelationshipsSubscription';
import type { LemonsqueezyApiResponseSelfLink } from './LemonsqueezyApiResponseSelfLink';
import {
    LemonsqueezyApiResponseSelfLinkFromJSON,
    LemonsqueezyApiResponseSelfLinkFromJSONTyped,
    LemonsqueezyApiResponseSelfLinkToJSON,
} from './LemonsqueezyApiResponseSelfLink';
import type { LemonsqueezySubscription } from './LemonsqueezySubscription';
import {
    LemonsqueezySubscriptionFromJSON,
    LemonsqueezySubscriptionFromJSONTyped,
    LemonsqueezySubscriptionToJSON,
} from './LemonsqueezySubscription';

/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
 */
export interface LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription {
    /**
     * 
     * @type {LemonsqueezySubscription}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
     */
    attributes?: LemonsqueezySubscription;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
     */
    id?: string;
    /**
     * 
     * @type {LemonsqueezyApiResponseSelfLink}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
     */
    links?: LemonsqueezyApiResponseSelfLink;
    /**
     * 
     * @type {LemonsqueezyApiResponseRelationshipsSubscription}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
     */
    relationships?: LemonsqueezyApiResponseRelationshipsSubscription;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
     */
    type?: string;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription interface.
 */
export function instanceOfLemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionFromJSON(json: any): LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription {
    return LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': !exists(json, 'attributes') ? undefined : LemonsqueezySubscriptionFromJSON(json['attributes']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'links': !exists(json, 'links') ? undefined : LemonsqueezyApiResponseSelfLinkFromJSON(json['links']),
        'relationships': !exists(json, 'relationships') ? undefined : LemonsqueezyApiResponseRelationshipsSubscriptionFromJSON(json['relationships']),
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionToJSON(value?: LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': LemonsqueezySubscriptionToJSON(value.attributes),
        'id': value.id,
        'links': LemonsqueezyApiResponseSelfLinkToJSON(value.links),
        'relationships': LemonsqueezyApiResponseRelationshipsSubscriptionToJSON(value.relationships),
        'type': value.type,
    };
}

