/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription } from './LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription';
import {
    LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionFromJSON,
    LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionFromJSONTyped,
    LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionToJSON,
} from './LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription';
import type { LemonsqueezyApiResponseJSONAPI } from './LemonsqueezyApiResponseJSONAPI';
import {
    LemonsqueezyApiResponseJSONAPIFromJSON,
    LemonsqueezyApiResponseJSONAPIFromJSONTyped,
    LemonsqueezyApiResponseJSONAPIToJSON,
} from './LemonsqueezyApiResponseJSONAPI';
import type { LemonsqueezyApiResponseSelfLink } from './LemonsqueezyApiResponseSelfLink';
import {
    LemonsqueezyApiResponseSelfLinkFromJSON,
    LemonsqueezyApiResponseSelfLinkFromJSONTyped,
    LemonsqueezyApiResponseSelfLinkToJSON,
} from './LemonsqueezyApiResponseSelfLink';

/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
 */
export interface LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription {
    /**
     * 
     * @type {LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription}
     * @memberof LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
     */
    data?: LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription;
    /**
     * 
     * @type {LemonsqueezyApiResponseJSONAPI}
     * @memberof LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
     */
    jsonapi?: LemonsqueezyApiResponseJSONAPI;
    /**
     * 
     * @type {LemonsqueezyApiResponseSelfLink}
     * @memberof LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription
     */
    links?: LemonsqueezyApiResponseSelfLink;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription interface.
 */
export function instanceOfLemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionFromJSON(json: any): LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription {
    return LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionFromJSON(json['data']),
        'jsonapi': !exists(json, 'jsonapi') ? undefined : LemonsqueezyApiResponseJSONAPIFromJSON(json['jsonapi']),
        'links': !exists(json, 'links') ? undefined : LemonsqueezyApiResponseSelfLinkFromJSON(json['links']),
    };
}

export function LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionToJSON(value?: LemonsqueezyApiResponseLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': LemonsqueezyApiResponseDataLemonsqueezySubscriptionLemonsqueezyApiResponseRelationshipsSubscriptionToJSON(value.data),
        'jsonapi': LemonsqueezyApiResponseJSONAPIToJSON(value.jsonapi),
        'links': LemonsqueezyApiResponseSelfLinkToJSON(value.links),
    };
}

