/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LemonsqueezyApiResponseLink
 */
export interface LemonsqueezyApiResponseLink {
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseLink
     */
    related?: string;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyApiResponseLink
     */
    self?: string;
}

/**
 * Check if a given object implements the LemonsqueezyApiResponseLink interface.
 */
export function instanceOfLemonsqueezyApiResponseLink(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyApiResponseLinkFromJSON(json: any): LemonsqueezyApiResponseLink {
    return LemonsqueezyApiResponseLinkFromJSONTyped(json, false);
}

export function LemonsqueezyApiResponseLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyApiResponseLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'related': !exists(json, 'related') ? undefined : json['related'],
        'self': !exists(json, 'self') ? undefined : json['self'],
    };
}

export function LemonsqueezyApiResponseLinkToJSON(value?: LemonsqueezyApiResponseLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'related': value.related,
        'self': value.self,
    };
}

