/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LemonsqueezyBillingAddress
 */
export interface LemonsqueezyBillingAddress {
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyBillingAddress
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof LemonsqueezyBillingAddress
     */
    zip?: string;
}

/**
 * Check if a given object implements the LemonsqueezyBillingAddress interface.
 */
export function instanceOfLemonsqueezyBillingAddress(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LemonsqueezyBillingAddressFromJSON(json: any): LemonsqueezyBillingAddress {
    return LemonsqueezyBillingAddressFromJSONTyped(json, false);
}

export function LemonsqueezyBillingAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): LemonsqueezyBillingAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': !exists(json, 'country') ? undefined : json['country'],
        'zip': !exists(json, 'zip') ? undefined : json['zip'],
    };
}

export function LemonsqueezyBillingAddressToJSON(value?: LemonsqueezyBillingAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'zip': value.zip,
    };
}

