/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelsBertAIResults } from './ModelsBertAIResults';
import {
    ModelsBertAIResultsFromJSON,
    ModelsBertAIResultsFromJSONTyped,
    ModelsBertAIResultsToJSON,
} from './ModelsBertAIResults';
import type { ModelsRobertaAIResults } from './ModelsRobertaAIResults';
import {
    ModelsRobertaAIResultsFromJSON,
    ModelsRobertaAIResultsFromJSONTyped,
    ModelsRobertaAIResultsToJSON,
} from './ModelsRobertaAIResults';

/**
 * 
 * @export
 * @interface ModelsYoutubeAnalysisResults
 */
export interface ModelsYoutubeAnalysisResults {
    /**
     * 
     * @type {ModelsBertAIResults}
     * @memberof ModelsYoutubeAnalysisResults
     */
    bertResults?: ModelsBertAIResults;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalysisResults
     */
    recommendationChatGpt?: string;
    /**
     * 
     * @type {ModelsRobertaAIResults}
     * @memberof ModelsYoutubeAnalysisResults
     */
    robertaResults?: ModelsRobertaAIResults;
}

/**
 * Check if a given object implements the ModelsYoutubeAnalysisResults interface.
 */
export function instanceOfModelsYoutubeAnalysisResults(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsYoutubeAnalysisResultsFromJSON(json: any): ModelsYoutubeAnalysisResults {
    return ModelsYoutubeAnalysisResultsFromJSONTyped(json, false);
}

export function ModelsYoutubeAnalysisResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsYoutubeAnalysisResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bertResults': !exists(json, 'bert_results') ? undefined : ModelsBertAIResultsFromJSON(json['bert_results']),
        'recommendationChatGpt': !exists(json, 'recommendation_chat_gpt') ? undefined : json['recommendation_chat_gpt'],
        'robertaResults': !exists(json, 'roberta_results') ? undefined : ModelsRobertaAIResultsFromJSON(json['roberta_results']),
    };
}

export function ModelsYoutubeAnalysisResultsToJSON(value?: ModelsYoutubeAnalysisResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bert_results': ModelsBertAIResultsToJSON(value.bertResults),
        'recommendation_chat_gpt': value.recommendationChatGpt,
        'roberta_results': ModelsRobertaAIResultsToJSON(value.robertaResults),
    };
}

