/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsYoutubeAnalyzerReqBody
 */
export interface ModelsYoutubeAnalyzerReqBody {
    /**
     * The email of the account sending the request
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerReqBody
     */
    accountEmail?: string;
    /**
     * The email that will be used to send the results
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerReqBody
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerReqBody
     */
    videoId?: string;
}

/**
 * Check if a given object implements the ModelsYoutubeAnalyzerReqBody interface.
 */
export function instanceOfModelsYoutubeAnalyzerReqBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsYoutubeAnalyzerReqBodyFromJSON(json: any): ModelsYoutubeAnalyzerReqBody {
    return ModelsYoutubeAnalyzerReqBodyFromJSONTyped(json, false);
}

export function ModelsYoutubeAnalyzerReqBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsYoutubeAnalyzerReqBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountEmail': !exists(json, 'account_email') ? undefined : json['account_email'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'videoId': !exists(json, 'video_id') ? undefined : json['video_id'],
    };
}

export function ModelsYoutubeAnalyzerReqBodyToJSON(value?: ModelsYoutubeAnalyzerReqBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_email': value.accountEmail,
        'email': value.email,
        'video_id': value.videoId,
    };
}

