/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { YoutubeComment } from './YoutubeComment';
import {
    YoutubeCommentFromJSON,
    YoutubeCommentFromJSONTyped,
    YoutubeCommentToJSON,
} from './YoutubeComment';

/**
 * 
 * @export
 * @interface ModelsYoutubeVideoNegativeCommentsRespBody
 */
export interface ModelsYoutubeVideoNegativeCommentsRespBody {
    /**
     * 
     * @type {number}
     * @memberof ModelsYoutubeVideoNegativeCommentsRespBody
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeVideoNegativeCommentsRespBody
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeVideoNegativeCommentsRespBody
     */
    previous?: string;
    /**
     * 
     * @type {Array<YoutubeComment>}
     * @memberof ModelsYoutubeVideoNegativeCommentsRespBody
     */
    results?: Array<YoutubeComment>;
}

/**
 * Check if a given object implements the ModelsYoutubeVideoNegativeCommentsRespBody interface.
 */
export function instanceOfModelsYoutubeVideoNegativeCommentsRespBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsYoutubeVideoNegativeCommentsRespBodyFromJSON(json: any): ModelsYoutubeVideoNegativeCommentsRespBody {
    return ModelsYoutubeVideoNegativeCommentsRespBodyFromJSONTyped(json, false);
}

export function ModelsYoutubeVideoNegativeCommentsRespBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsYoutubeVideoNegativeCommentsRespBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(YoutubeCommentFromJSON)),
    };
}

export function ModelsYoutubeVideoNegativeCommentsRespBodyToJSON(value?: ModelsYoutubeVideoNegativeCommentsRespBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(YoutubeCommentToJSON)),
    };
}

