/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsYoutubePreAnalyzerReqBody
 */
export interface ModelsYoutubePreAnalyzerReqBody {
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubePreAnalyzerReqBody
     */
    videoId?: string;
}

/**
 * Check if a given object implements the ModelsYoutubePreAnalyzerReqBody interface.
 */
export function instanceOfModelsYoutubePreAnalyzerReqBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsYoutubePreAnalyzerReqBodyFromJSON(json: any): ModelsYoutubePreAnalyzerReqBody {
    return ModelsYoutubePreAnalyzerReqBodyFromJSONTyped(json, false);
}

export function ModelsYoutubePreAnalyzerReqBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsYoutubePreAnalyzerReqBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'videoId': !exists(json, 'video_id') ? undefined : json['video_id'],
    };
}

export function ModelsYoutubePreAnalyzerReqBodyToJSON(value?: ModelsYoutubePreAnalyzerReqBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'video_id': value.videoId,
    };
}

