/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ModelsYoutubeAnalysisLandingResults } from './ModelsYoutubeAnalysisLandingResults';
import {
    ModelsYoutubeAnalysisLandingResultsFromJSON,
    ModelsYoutubeAnalysisLandingResultsFromJSONTyped,
    ModelsYoutubeAnalysisLandingResultsToJSON,
} from './ModelsYoutubeAnalysisLandingResults';

/**
 * 
 * @export
 * @interface ModelsYoutubeAnalyzerLandingRespBody
 */
export interface ModelsYoutubeAnalyzerLandingRespBody {
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerLandingRespBody
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerLandingRespBody
     */
    email?: string;
    /**
     * 
     * @type {ModelsYoutubeAnalysisLandingResults}
     * @memberof ModelsYoutubeAnalyzerLandingRespBody
     */
    results?: ModelsYoutubeAnalysisLandingResults;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerLandingRespBody
     */
    videoId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerLandingRespBody
     */
    videoTitle?: string;
}

/**
 * Check if a given object implements the ModelsYoutubeAnalyzerLandingRespBody interface.
 */
export function instanceOfModelsYoutubeAnalyzerLandingRespBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsYoutubeAnalyzerLandingRespBodyFromJSON(json: any): ModelsYoutubeAnalyzerLandingRespBody {
    return ModelsYoutubeAnalyzerLandingRespBodyFromJSONTyped(json, false);
}

export function ModelsYoutubeAnalyzerLandingRespBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsYoutubeAnalyzerLandingRespBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'results': !exists(json, 'results') ? undefined : ModelsYoutubeAnalysisLandingResultsFromJSON(json['results']),
        'videoId': !exists(json, 'video_id') ? undefined : json['video_id'],
        'videoTitle': !exists(json, 'video_title') ? undefined : json['video_title'],
    };
}

export function ModelsYoutubeAnalyzerLandingRespBodyToJSON(value?: ModelsYoutubeAnalyzerLandingRespBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'created_at': value.createdAt,
        'email': value.email,
        'results': ModelsYoutubeAnalysisLandingResultsToJSON(value.results),
        'video_id': value.videoId,
        'video_title': value.videoTitle,
    };
}

