/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsYoutubeAnalyzerRespBody
 */
export interface ModelsYoutubeAnalyzerRespBody {
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerRespBody
     */
    accountEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerRespBody
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerRespBody
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerRespBody
     */
    lastUpdate?: string;
    /**
     * firestore results id
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerRespBody
     */
    resultsId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerRespBody
     */
    videoId?: string;
}

/**
 * Check if a given object implements the ModelsYoutubeAnalyzerRespBody interface.
 */
export function instanceOfModelsYoutubeAnalyzerRespBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsYoutubeAnalyzerRespBodyFromJSON(json: any): ModelsYoutubeAnalyzerRespBody {
    return ModelsYoutubeAnalyzerRespBodyFromJSONTyped(json, false);
}

export function ModelsYoutubeAnalyzerRespBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsYoutubeAnalyzerRespBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountEmail': !exists(json, 'account_email') ? undefined : json['account_email'],
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'lastUpdate': !exists(json, 'last_update') ? undefined : json['last_update'],
        'resultsId': !exists(json, 'results_id') ? undefined : json['results_id'],
        'videoId': !exists(json, 'video_id') ? undefined : json['video_id'],
    };
}

export function ModelsYoutubeAnalyzerRespBodyToJSON(value?: ModelsYoutubeAnalyzerRespBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account_email': value.accountEmail,
        'created_at': value.createdAt,
        'email': value.email,
        'last_update': value.lastUpdate,
        'results_id': value.resultsId,
        'video_id': value.videoId,
    };
}

