/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsYoutubeAnalyzerLandingReqBody
 */
export interface ModelsYoutubeAnalyzerLandingReqBody {
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerLandingReqBody
     */
    videoId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsYoutubeAnalyzerLandingReqBody
     */
    videoTitle?: string;
}

/**
 * Check if a given object implements the ModelsYoutubeAnalyzerLandingReqBody interface.
 */
export function instanceOfModelsYoutubeAnalyzerLandingReqBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModelsYoutubeAnalyzerLandingReqBodyFromJSON(json: any): ModelsYoutubeAnalyzerLandingReqBody {
    return ModelsYoutubeAnalyzerLandingReqBodyFromJSONTyped(json, false);
}

export function ModelsYoutubeAnalyzerLandingReqBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsYoutubeAnalyzerLandingReqBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'videoId': !exists(json, 'video_id') ? undefined : json['video_id'],
        'videoTitle': !exists(json, 'video_title') ? undefined : json['video_title'],
    };
}

export function ModelsYoutubeAnalyzerLandingReqBodyToJSON(value?: ModelsYoutubeAnalyzerLandingReqBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'video_id': value.videoId,
        'video_title': value.videoTitle,
    };
}

