/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ModelsSubscriptionPlanSlug = {
    FREE: 0,
    HOBBY: 1,
    POPULAR: 2
} as const;
export type ModelsSubscriptionPlanSlug = typeof ModelsSubscriptionPlanSlug[keyof typeof ModelsSubscriptionPlanSlug];


export function ModelsSubscriptionPlanSlugFromJSON(json: any): ModelsSubscriptionPlanSlug {
    return ModelsSubscriptionPlanSlugFromJSONTyped(json, false);
}

export function ModelsSubscriptionPlanSlugFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsSubscriptionPlanSlug {
    return json as ModelsSubscriptionPlanSlug;
}

export function ModelsSubscriptionPlanSlugToJSON(value?: ModelsSubscriptionPlanSlug | null): any {
    return value as any;
}

