/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YoutubeThumbnail
 */
export interface YoutubeThumbnail {
    /**
     * Height: (Optional) Height of the thumbnail image.
     * @type {number}
     * @memberof YoutubeThumbnail
     */
    height?: number;
    /**
     * Url: The thumbnail image's URL.
     * @type {string}
     * @memberof YoutubeThumbnail
     */
    url?: string;
    /**
     * Width: (Optional) Width of the thumbnail image.
     * @type {number}
     * @memberof YoutubeThumbnail
     */
    width?: number;
}

/**
 * Check if a given object implements the YoutubeThumbnail interface.
 */
export function instanceOfYoutubeThumbnail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function YoutubeThumbnailFromJSON(json: any): YoutubeThumbnail {
    return YoutubeThumbnailFromJSONTyped(json, false);
}

export function YoutubeThumbnailFromJSONTyped(json: any, ignoreDiscriminator: boolean): YoutubeThumbnail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'height': !exists(json, 'height') ? undefined : json['height'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'width': !exists(json, 'width') ? undefined : json['width'],
    };
}

export function YoutubeThumbnailToJSON(value?: YoutubeThumbnail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'height': value.height,
        'url': value.url,
        'width': value.width,
    };
}

