/* tslint:disable */
/* eslint-disable */
/**
 * GPTube API swagger docs
 * This is the API documentation of GPTube
 *
 * The version of the OpenAPI document: 1.0
 * Contact: luckly083@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YoutubeVideoLocalization
 */
export interface YoutubeVideoLocalization {
    /**
     * Description: Localized version of the video's description.
     * @type {string}
     * @memberof YoutubeVideoLocalization
     */
    description?: string;
    /**
     * Title: Localized version of the video's title.
     * @type {string}
     * @memberof YoutubeVideoLocalization
     */
    title?: string;
}

/**
 * Check if a given object implements the YoutubeVideoLocalization interface.
 */
export function instanceOfYoutubeVideoLocalization(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function YoutubeVideoLocalizationFromJSON(json: any): YoutubeVideoLocalization {
    return YoutubeVideoLocalizationFromJSONTyped(json, false);
}

export function YoutubeVideoLocalizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): YoutubeVideoLocalization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'title': !exists(json, 'title') ? undefined : json['title'],
    };
}

export function YoutubeVideoLocalizationToJSON(value?: YoutubeVideoLocalization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'title': value.title,
    };
}

