# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gptube-api-v2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0D07F6CAEBA341C1A66150AFBB345AC8 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_DB4AE85EDB764B6BAFD4E7938DDCBD15 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:go-server"
          push: true
          tags: index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0D07F6CAEBA341C1A66150AFBB345AC8 }}/gptube:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "gptube-api-v2"
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_370DA89BD09F42E1A0F1A878F8CE0131 }}
          images: "index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_0D07F6CAEBA341C1A66150AFBB345AC8 }}/gptube:${{ github.sha }}"
